################################################################
# Global configuration
################################################################
log_format = "json"
log_level = "error"
log_file = "/var/log/remco.log"


################################################################
# Resource configuration
################################################################
[[resource]]
  name = "dhis2"

  [[resource.template]]
    src = "/etc/remco/templates/dhis2/dhis.conf.tmpl"
    dst = "/opt/dhis2/dhis.conf"

  [resource.backend]
    [resource.backend.env]
      onetime = false
      interval = 60
      keys = ["/dhis2/","/service/name","/system/ip"]

  [resource.exec]
    command = "catalina.sh run"
    kill_timeout = 30
    splay = 30
