---

services:

  database:
    # Options "synchronous_commit" through "max_locks_per_transaction" are some of the DHIS2 recommendations (https://docs.dhis2.org/en/manage/performing-system-administration/dhis-core-version-236/installation.html#install_postgresql_installation) (other values may be higher or different if from PGTune)
    # Options "shared_buffers" through "max_parallel_maintenance_workers" are PGTune with: version=14, os=linux, type=web, ram=4GB, cpus=2, conns=40, storage=ssd
    # Options "fsync" through "full_page_writes" are to improve performance (https://github.community/t/how-do-i-properly-override-a-service-entrypoint/17435/8)
    command: >
      postgres
        -c "listen_addresses=*"
        -c "synchronous_commit=off"
        -c "wal_writer_delay=10000ms"
        -c "max_locks_per_transaction=96"
        -c "shared_buffers=1GB"
        -c "effective_cache_size=3GB"
        -c "maintenance_work_mem=256MB"
        -c "checkpoint_completion_target=0.9"
        -c "wal_buffers=16MB"
        -c "default_statistics_target=100"
        -c "random_page_cost=1.1"
        -c "effective_io_concurrency=200"
        -c "work_mem=26214kB"
        -c "min_wal_size=1GB"
        -c "max_wal_size=4GB"
        -c "max_worker_processes=2"
        -c "max_parallel_workers_per_gather=1"
        -c "max_parallel_workers=2"
        -c "max_parallel_maintenance_workers=1"
        -c "fsync=off"
        -c "full_page_writes=off"

  dhis2:
    environment:
      CATALINA_OPTS: "-Xms1536M -Xmx1536M"
      DHIS2_CONNECTION_POOL_MAXSIZE: 40
